export enum UserRole {
    BROKER_EXTERNO = 'BROKER_EXTERNO',
    EJECUTIVO_PROMESA = 'EJECUTIVO_PROMESA',
    EJECUTIVO_ESCRITURA = 'EJECUTIVO_ESCRITURA',
    EJECUTIVO_CREDITO = 'EJECUTIVO_CREDITO',
    CONTABILIDAD = 'CONTABILIDAD',
    GERENCIA = 'GERENCIA',
    ADMIN = 'ADMIN',
}
